services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_MODELS=tinyllama
      - OLLAMA_AUTO_PULL=true
    restart: always

  backend:
    build: ./backend
    depends_on:
      - ollama
    environment:
      - OLLAMA_API_URL=http://ollama:11434/api/generate
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8501:8501"
    restart: always

volumes:
  ollama_data:
